### ISSUE TITLE
Media directories

### ISSUE THREAD

**Issue by carlosgj94** [tebiondl/tebiondl.github.io#1]
You probably want to split your files into different sections and not having your files in the root of the project. I nice update could be:
- img: Put all your images in here. ALL.
- css: Put all your css's in here. ALL.
- media: The video
- fonts: It's obvious
- scripts: The js files

The index.html is fine where it is, but if you add more you probably want to make them a directory as well.

**Comment by tebiondl** [comment]
Ya lo he arreglado, pero no me deja cambiar de sitio ni la imagen de fondo, ni el css en el que la referencio
